backend:
  name: github
  repo: xivresources/glossary.xivresources.com
  branch: main # Branch to update (optional; defaults to master)
  base_url: https://auth.xivresources.com
  site_domain: glossary.xivresources.com
  cms_label_prefix: cms/
publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img
site_url: https://glossary.xivresources.com
show_preview_links: true
collections:
  - name: 'terms'
    label: 'Terms'
    label_singular: 'Term'
    folder: 'content'
    create: true
    slug: '{{slug}}'
    preview_path: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: "Alias URLs"
        name: "aliases"
        hint: "Enter alias urls which have leading and trailing slashes. For example, set an alias for `/area-of-effect/` to `/aoe/`"
        required: false
        widget: "list"
      - { label: 'Opengraph Description', name: 'description', widget: 'string', required: false }
      - label: 'Opengraph Image(s)'
        name: 'images'
        widget: 'list'
        field: {label: 'Image', name: 'image', widget: 'image'}
